FROM carqualifier/docker-nginx-php:php70

ADD ./container-files/aerospike-client-php-3.4.14.tar.gz /tmp/
ADD ./container-files/aerospike.ini /etc/php.d/20-aerospike.ini


RUN \
    ls -al /opt/remi/php70/root/usr/bin && \
    echo $PATH && \
    export PATH=$PATH:/opt/remi/php70/root/usr/bin:/opt/remi/php70/root/usr/sbin:/opt/remi/php70/root/usr/bin:/opt/remi/php70/root/usr/sbin && \
   echo $PATH
